# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GriefConnect' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GriefConnect
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'GriefConnectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GriefConnectUITests' do
    # Pods for testing
  end

end
